apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
          - name: tls.crt
            valueFrom:
              secretKeyRef:
                name: my-tls-secret
                key: tls.crt
          - name: tls.key
            valueFrom:
              secretKeyRef:
                name: my-tls-secret
                key: tls.key
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: my-configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Заголовок</title>
    </head>
    <body>
        <h1>Hello, Netology</h1>        
    </body>
    </html>

---
apiVersion: v1
kind: Secret
metadata:
  name: my-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQyekNDQXNPZ0F3SUJBZ0lVZHJrRDQyaXNjbEtnSjRMUmlKek1VOHVnSmxnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2ZURUxNQWtHQTFVRUJoTUNVbFV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeEV6QVJCZ05WQkFjTQpDbE5sZG1GemRHOXdiMnd4RVRBUEJnTlZCQW9NQ0U1bGRHOXNiMmQ1TVE0d0RBWURWUVFEREFWQmJuUnZiakVoCk1COEdDU3FHU0liM0RRRUpBUllTWW1GeVlXNXJiM1pBZVdGdVpHVjRMbkoxTUI0WERUSTBNREl5T1RFM01USTAKT0ZvWERUSTFNREl5T0RFM01USTBPRm93ZlRFTE1Ba0dBMVVFQmhNQ1VsVXhFekFSQmdOVkJBZ01DbE52YldVdApVM1JoZEdVeEV6QVJCZ05WQkFjTUNsTmxkbUZ6ZEc5d2Iyd3hFVEFQQmdOVkJBb01DRTVsZEc5c2IyZDVNUTR3CkRBWURWUVFEREFWQmJuUnZiakVoTUI4R0NTcUdTSWIzRFFFSkFSWVNZbUZ5WVc1cmIzWkFlV0Z1WkdWNExuSjEKTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2VGFhTkVGVEVDek5PVFdzZ0d4Nwo2SjVjTlhPem1uWGxDNVBvcDEzMEgreUlaWWN5SkQ4MFlzODhkTHArQ0ZHMDZ0OURFN25RejVONTlkOG1EcEQ2CmR0Tm9GVkQ4N0RZS2xVRUM1SjhhZGVIQ2sxQUFpbTN4QXM3b0JZOWV4Y0NpZitoVFZGTFZ2ZEJpQ2R1Q1ZrUXkKSk51bVRLa0g4dk5TZ1lKZ0lWeUZSNVNBUERVb2tjVm5RSVZtL0VNRy94aFd2bytteklTN1NmV0pFcVQxbnJxRAp1ODJIS25DRTRaUXRLYmJIZmtLNGREUzE3dHFicEhkS1E2MUxtZ2dINnEvcC8zNVh6N3RnTXY0dEk2UlVrdFJZCkVuZ0JSMjVGWmZpbmJBVVlFMS9ZUWxNTE02SlJWWFRHOXNKcTJ3TzJVSHhiWnlpaFhLTWRJOVpXbys2a0lneTYKNFFJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVTJzb0dYMHZSOUxzOUVhYkt2NjNKT0tqRjF1Y3dId1lEVlIwagpCQmd3Rm9BVTJzb0dYMHZSOUxzOUVhYkt2NjNKT0tqRjF1Y3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txCmhraUc5dzBCQVFzRkFBT0NBUUVBdkNkdVVvSDhZZklPQlludTMwdlRoQmhGdUpBNGxCck5mTUhnM3JPbk1xa0MKU0JvcVorQmN4bStCZnFtQi9XTUZROUw1VnRzYVJVMGk4My85U1RKQjJHeERmQ01NMHI4OW90UkwzMXVzYUN3NgpRWmFNd25IaWlVZVZCSy9OVVVwYkFsbldWS0Fvd1dpaGlnb2hPYldPdEJuSU9TVlJpT0VHbyt1bXhIWStia09GCnE4Q1BucEcxVjEvYnBodnhpbnM4clp5WXIrRy9mVHZBZnVPc2ZhMU1oRVVNRXlRbm5KMm5Zd0hYeWg0bUpZVFQKMmNFQUtaYm1NOThVR1BMSDZBMmlNejNnTDUrTzZlaHU5RjBOcGtldXlIdHZTL1NHMkRsSDhsbDBzNWNzZGFNKwpJSWFmc2sxVE5EWUo1OE1LRFBnbGFLT3V6Um9wcEYyTVFhNGQ5dmNzTHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzlOcG8wUVZNUUxNMDUKTmF5QWJIdm9ubHcxYzdPYWRlVUxrK2luWGZRZjdJaGxoeklrUHpSaXp6eDB1bjRJVWJUcTMwTVR1ZERQazNuMQozeVlPa1BwMjAyZ1ZVUHpzTmdxVlFRTGtueHAxNGNLVFVBQ0tiZkVDenVnRmoxN0Z3S0ovNkZOVVV0VzkwR0lKCjI0SldSRElrMjZaTXFRZnk4MUtCZ21BaFhJVkhsSUE4TlNpUnhXZEFoV2I4UXdiL0dGYStqNmJNaEx0SjlZa1MKcFBXZXVvTzd6WWNxY0lUaGxDMHB0c2QrUXJoME5MWHUycHVrZDBwRHJVdWFDQWZxcituL2ZsZlB1MkF5L2kwagpwRlNTMUZnU2VBRkhia1ZsK0tkc0JSZ1RYOWhDVXdzem9sRlZkTWIyd21yYkE3WlFmRnRuS0tGY294MGoxbGFqCjdxUWlETHJoQWdNQkFBRUNnZ0VBR2VDVTJGNnl3SHlRR0tucGpLckppM2ZVL281eldzV1M3TEZ1MlN6MVRVUnAKSnhHRlh3V3g0VzJjUkE2WlhBUG9yVktaZHVJcjE2ZkF2MHFraHN0M0piY2wvZnhVaXUyZEp1cDhQYzR3clR5UwpBdG1uS1VkOTliZGNiaDQ4aE9raWtFR3kyODUwWXdCVDJDdElPUW9jbllQWXk1VTJmQmloQ1F0T29HRnA3Tzc2CjkwZmpFUUM2dHRXYnpXaVllY2pEeHJVQUE0UDVjdFRBYk1HOVJ1WWFpVm5yOTFPenVKQ1g4T2VqSGV4VXI0TEoKMlJXc0pRTkdSUmh1TGZsUDQreDNxMXFSUlUxT3hmSjJ2ZlhMUXIwalIyaW1QQ1NYMEpFSjlFZ2JDMWdoOEtyMwppYXlVcnhNUmJFTHd2QXhCSVVKU2kyaUU3TlZKdDVRcVYxODAzMVJMUFFLQmdRRHRaUHdabXAxSXZ4RnJhTFpwCnB5Q1lHb2J6OVNtYUszN1o3ai9YQjljOXJXZFk3RDhINy9xWnhyQ01IeWZHWWR5QkUwU2ZjYzZiVGE0M3JnRWkKNjAvTE53ZklKMTFlZzE4NVNSWTlzaEs0UmUwSXdGdG9RMHlYOTdVRFpkd1VHZEJBUDRVelVYRHovbnB4UmJhUQpRMUVxSkt5U0pOYzdlVHNiR1BrbXZMNzYwd0tCZ1FETUN1eVBVMXc1WGNVakthRnBOUlk3bGQrcHhidlA4NlRHCms3SW1YbHBkUEVqejZacEFhZDFzblRlSGNiNU5WTkt5dEhoR05lNTdCbDd6di9FaVhzcGFlNEs5UHdPNGF1VHcKSU9xSnJuS1FnTGFRL3k1bURuUlprQy8vR2NtbUpUcWNiOEV4NTVNTU1zdEdJUnlza0N0SW9ZbGphSVJSZld6RAp4SDdXUElNNit3S0JnUUNYWjU2NW5iak9tcjI3YVU5ZDF1K2MwdDViWFhNcEZyQ1N3YmNKcDhDSlg3ellJK1NYClpXREpEc1d1dUhnZnVHNXdEQi9xS1NXQ08ycnZyQlNoZHI2dmR1dUpwa0dRYyswWmxobVBRN0ZZd1pCSjBwVDUKekdKZlVlYXF3aDQ0MjdYTUpEY0o0ZGxPWkhFbktUVWtrU3FFM0ZzTDRsODdXVGh2TWVCRjZuOUxiUUtCZ1FESApJczQzSDFzOW5aZWR0cTZTZUQ0bmp5RUhselN5UW82SlEzSTE0aFg5TXEzY1p4dWxTK3pQYVN6ZG9wUGc4eXpqClBpQzRIVUNQanVzeXB4eVd0NzV6eW1FUmc2T0U0OFpsMlNvdGp6UytkUEE0Mk9PV3RQcTJ3bk1sWEN5aVcyazEKYmhnMk5WVWRMYUdYNHc4U0YyNDI1M2luclVTZUozUDBLQnpGeDY4bjZ3S0JnQW1WVzcwbHNOcmMyME03WWF0QQpsZkJYSzJBdmxnb3lqTWFvcG11R3RkSEpsUC82c2VaUjV0dFROY01sUFZJNGcvcGw1SW8wUTJqQ0Jaem9DTE1aCk1ncWFiaHhWTDdlRUNyd0FjQ2FaMXh5cjJOQ3FoOC9sU255T1lYcngrVTR0UFhDMkEwaS9Oa2YvKzFIZXI4NU4KL0RsOFVUaVI3VE5MUVlMNWJIRTg0a2lICi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K