apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
  namespace: lesson3
  labels:
    app: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        command: ['sh', '-c', 'while true; do cat /output/data.txt; sleep 5; done']
        volumeMounts:
        - name: my-volume
          mountPath: /output
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'i=1; while true; do echo "Data Netology $i" >> /input/data.txt; i=$((i+1)); sleep 5; done']
        volumeMounts:
        - name: my-volume
          mountPath: /input
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: pvc-manual

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-manual
  namespace: lesson3
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-manual
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv
  persistentVolumeReclaimPolicy: Recycle