apiVersion: v1
kind: Pod
metadata:
  labels:
    app: echoserver
  name: netology-web
spec:
  containers:
  - name: echoserver-kuber
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: echoserver
  ports:
    - name: web
      port: 8080